### PR TITLE
default=False set on boolean fields

### PR DESCRIPTION
**Pull request by freakypie**
for django compatibility

### CODE REVIEW

**Comment by littlepea** [comment]
Seems related to #116

**Comment by littlepea** [comment]
It's been a few months, why not merge it?

**Comment by theju** [comment]
@littlepea We will have a look at this and other tickets very soon.

**Comment by theju** [comment]
Committed in [b83f13318cd723e7a1ed9158d5833bd6db594eec]. Thanks @freakypie

**Pull request closed without merging**
